name: Update AUR Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      pkgver:
        description: 'New package version'
        required: true
        type: string

jobs:
  aur-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update PKGBUILD and push to AUR
        uses: kamack38/pkgbuild-update@v2.1.0
        id: update
        with:
          path: .
          pkgver: ${{ github.event.release.tag_name || inputs.pkgver }}
          pkgrel: 1
          updpkgsums: true
          srcinfo: true
          aur_pkgname: dotfiles-installer
          aur_commit_username: ${{ secrets.AUR_USERNAME }}
          aur_commit_email: ${{ secrets.AUR_EMAIL }}
          aur_ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
